### PR TITLE
Add size to listing

### PR DESCRIPTION
**Pull request by dhinakg**

### CODE REVIEW

**Comment by dhinakg** [comment]
@corpnewt pls

**Comment by dhinakg** [comment]
@corpnewt pls it's been 4 weeks

**Comment by corpnewt** [comment]
Still under review as this is far too major a change for one person to adequately comb through in any reasonable amount of time.

-CorpNewt

**Comment by dhinakg** [comment]
Did you get past the first line yet

**Comment by corpnewt** [comment]
Uh... not yet.  I'm at line -1

-CorpNewt

**Pull request closed without merging**
